CREATE TABLE CUSTOMERS
(
	ID INT NOT NULL PRIMARY KEY,
	FIRST_NAME varchar(50),
	LAST_NAME varchar(50),
	COMPANY varchar(50),
	MAIL varchar(50),
	PHONE VARCHAR(15),
	MOBILE VARCHAR(15),
	NOTES VARCHAR(255),
	ACTIVE BOOLEAN
);

CREATE TABLE ORDERS
(
	ID int NOT NULL PRIMARY KEY,
	LABEL varchar(50),
	ADR_ET DECIMAL,
	NUMBER_OF_DAYS DECIMAL,
	TVA DECIMAL,
	STATUS VARCHAR(30),
	TYPE VARCHAR(100),
	NOTES VARCHAR(255),
	CUSTOMER_ID INT
);
